name: catpred_new

channels:
  - pytorch
  - conda-forge
  - pyg
dependencies:
  - python=3.9
  - matplotlib>=3.1.3
  - numpy>=1.18.1
  - pandas>=1.0.3
  - pandas-flavor>=0.2.0
  - pip>=20.0.2
  - pytorch>=1.11.0
  - scikit-learn>=0.22.2.post1
  - scipy>=1.4.1
  - tensorboardX>=2.0
  - torchvision>=0.5.0
  - tqdm>=4.45.0
  - faiss-cpu
  - pytorch-scatter
  - pyg
  - kimlab::stride
  - pip:
    - ipdb
    - fair-esm
    - progres
    - rdkit-pypi
    - transformers
    - descriptastorus
    - sentencepiece
    - seaborn
    - rotary_embedding_torch==0.6.5
    - typed-argument-parser>=1.6.1
